import { IUser } from '@/api/type';

export const users: IUser[] = [
  {
    id: 1,
    username: 'admin',
    role: 'admin',
    company: 'isocked.com',
    job: 'Developer',
    country: 'China',
    city: 'Shenzhen',
    phone: '(+86) 4567-8900',
    email: 'wangqiangshen@gmail.com',
    status: 'active',
    avatar: '/assets/images/users/avatar-1.jpg',
    access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTB9.txWLuN4QT5PqTtgHmlOiNerIu5Do51PpYOiZutkyXYg'
  },
  {
    id: 2,
    username: 'Jane Wilison',
    role: 'author',
    company: 'ESG',
    job: 'Designer',
    country: 'USA',
    city: 'New York',
    phone: '(+123) 4567-8900',
    email: 'jane.wilison@test.com',
    status: 'pending',
    avatar: '/assets/images/avatars/avatar-2.png'
  },
  {
    id: 3,
    username: 'John Doe',
    role: 'author',
    company: 'ESG',
    job: 'Designer',
    country: 'USA',
    city: 'New York',
    phone: '(+123) 4567-8900',
    email: 'john.doe@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-3.png'
  },
  {
    id: 4,
    username: 'John Will',
    role: 'author',
    company: 'ESG',
    job: 'Project Manager',
    country: 'USA',
    city: 'New York',
    phone: '(+123) 4567-8900',
    email: 'john.will@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-4.png'
  },
  {
    id: 5,
    username: 'Maggy Hurran',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'Canada',
    city: 'Wotawa',
    phone: '(669) 914-1078',
    email: 'maggy.hurran@test.com',
    status: 'pending',
    avatar: '/assets/images/avatars/avatar-5.png'
  },
  {
    id: 6,
    username: 'Silvain Lane',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'USA',
    city: 'Boston',
    phone: '(+123) 914-1078',
    email: 'maggy.hurran@test.com',
    status: 'pending',
    avatar: '/assets/images/avatars/avatar-6.png'
  },
  {
    id: 7,
    username: 'Shane Black',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'USA',
    city: 'Huston',
    phone: '(+123) 914-1078',
    email: 'shane.black@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-7.png'
  },
  {
    id: 8,
    username: 'Jacob Hukins',
    role: 'author',
    company: 'ESG',
    job: 'Designer',
    country: 'USA',
    city: 'Huston',
    phone: '(+123) 456-789',
    email: 'jacob.hukins@test.com',
    status: 'pending',
    avatar: '/assets/images/avatars/avatar-8.png'
  },
  {
    id: 9,
    username: 'Priscilla Lung',
    role: 'author',
    company: 'ESG',
    job: 'Designer',
    country: 'China',
    city: 'HongKong',
    phone: '(+123) 456-789',
    email: 'priscilla.lung@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-9.png'
  },
  {
    id: 10,
    username: 'Bruce Russel',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'China',
    city: 'TianJin',
    phone: '(+123) 456-789',
    email: 'Bruce.Russel@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-10.png'
  },
  {
    id: 11,
    username: 'Brain Pena',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'UK',
    city: 'London',
    phone: '(+123) 456-789',
    email: 'brain.pena@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-1.png'
  },
  {
    id: 12,
    username: 'Kristin Tina',
    role: 'author',
    company: 'ESG',
    job: 'Developer',
    country: 'UK',
    city: 'London',
    phone: '(+123) 456-789',
    email: 'kristin.tina@test.com',
    status: 'active',
    avatar: '/assets/images/avatars/avatar-2.png'
  }
];
